version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # ✅ Ensure Python 3.9 is installed
    commands:
      - echo "Installing Terraform..."
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.3.0/terraform_1.3.0_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform version

  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/infrastructure 
      - echo "Setting up Terraform backend..."
      - aws s3 cp s3://$TF_BUCKET/backend.tf backend.tf || true
      - terraform init

  build:
    commands:
      - echo "Running Terraform Plan..."
      - terraform plan -out=tfplan
      - echo "Terraform Plan completed."

  post_build:
    commands:
      - echo "Uploading Terraform Plan to S3..."
      - aws s3 cp tfplan s3://terraform-state-gbvcdu43/tfplan
      - echo "Running Terraform Apply..."
      - terraform apply "tfplan"
      - echo "Build and deployment completed successfully."

artifacts:
  files:
    - tfplan
  discard-paths: yes
