version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # ✅ Ensure Python 3.9 is installed
    commands:
      - echo "Installing Terraform..."
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.3.0/terraform_1.3.0_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform version

  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/infrastructure 
      - echo "Setting up Terraform backend..."
      - terraform init

  build:
    commands:
      - echo "Running Terraform Plan..."
      - cd $CODEBUILD_SRC_DIR/infrastructure 
      - terraform plan -out=${CODEBUILD_SRC_DIR}/tfplan
      - echo "Terraform Plan completed."

  post_build:
    commands:
      - echo "Running Terraform Apply..."
      - cd ${CODEBUILD_SRC_DIR}/infrastructure
      - terraform init
      - terraform apply "${CODEBUILD_SRC_DIR}/tfplan"
      - echo "Build and deployment completed successfully."
